### ISSUE TITLE
the parameter of "downsample_n" 

### ISSUE THREAD

**Issue by luoht520** [tanaylab/metacell#27]
hi,
how to change the parameter of "downsample_n" when running  mcell_add_gene_stat?
Thanks

Louis

**Comment by aviezerl** [comment]
Hi Louis, 

You can change the parameters by setting it in your yaml config file, or by running the following command (e.g. if you want to change it to 1000): 

```r
tgconfig::set_param("scm_n_downsamp_gstat", 1000, "metacell")
```

Best, 
Aviezer

**Comment by luoht520** [comment]
> Hi Louis,
> 
> You can change the parameters by setting it in your yaml config file, or by running the following command (e.g. if you want to change it to 1000):
> 
> ```r
> tgconfig::set_param("scm_n_downsamp_gstat", 1000, "metacell")
> ```
> 
> Best,
> Aviezer

Thank you very much, I've got it!

Louis
