### ISSUE TITLE
number of metacells

### ISSUE THREAD

**Issue by andjedid** [tanaylab/metacell#33]
Hi,

Is it possible to increase the number of Metacells to more than 200 (between 800 and 1000) ? 

Thanks a lot,

Anissa

**Comment by amostanay** [comment]
Metacells' size is determined (but not in a one-to-one fashion) by the Knn parameter of the metacell graph and by the min metacell size parameter. If the Knn is smaller and the min metacell size is smaller, you will get more metacells. However - this is not recommended - metacell size should allow for a sufficient number of UMIs to defined the metacell gene expression distribution - of if you plan to move from ~100 cells (or ~200-400k UMIs) per metacell to 20 cells and 40k-80l umis per metacell, you may end up losing a lot of the parametric robustness that a good MC cover should provide you.

More direct control on the target number of UMIs/metacell is coming up in the next major version of the algorithm...
