### ISSUE TITLE
typo in function gen_fig_cmp_dir in atlas.r

### ISSUE THREAD

**Issue by mmittnenzweig** [tanaylab/metacell#36]
The line

fig_cmp_dir = paste(.scfigs_base, fig_cmp_dir,sep="")

should be

fig_cmp_dir = paste(.scfigs_base, fig_cmp_dir,sep="/")

instead (the sep option should contain "/").

**Comment by amostanay** [comment]
Done - (feel free to push such typo fixes - this wasn't killing scripts that did scfig_init("figs/")..
