### ISSUE TITLE
how can  i  read seurat object  into  metacell? 

### ISSUE THREAD

**Issue by tuqiang2014** [tanaylab/metacell#38]
how can  i  read seurat object  into  metacell?

**Comment by aviezerl** [comment]
You can use the [scm_import_sce_to_mat](https://tanaylab.github.io/metacell/reference/scm_import_sce_to_mat.html) function to convert SingleCellExperiment into a metacell umi matrix, e.g.:

```r
libray(Seurat)
sce = Convert(seurat_obj, "sce")
mat = scm_import_sce_to_mat(sce)
```

See also: [Interoperability with other scRNA formats](https://tanaylab.github.io/metacell/articles/e-data_convert.html)

**Comment by zhenzuo2** [comment]
Convert() cannot be found. use as.SingleCellExperiment() instead
https://satijalab.org/seurat/archive/v3.1/conversion_vignette.html

**Comment by Benfeitas** [comment]
Hi, could you please comment on how to setup `mat_nm` for subsequent analysis as shown in the vignette (e.g. `mcell_plot_umis_per_cell` in [here](https://tanaylab.github.io/metacell/reference/mcell_plot_umis_per_cell.html)("test"))
