### ISSUE TITLE
Gene quantification in metacells

### ISSUE THREAD

**Issue by nessa0389** [tanaylab/metacell#40]
How to find out the quantity of a particular gene in each metacell?
Is there a Metacell function that answers that?

**Comment by akhiadber** [comment]
The mc@e_gc matrix is a genes by metacells matrix with the normalized fractions for each gene in each metacell. If you a looking for the UMI sum per gene per metacell, you can try something like:
`mc_sums = tgs_matrix_tapply(mat@mat[,names(mc@mc)], mc@mc, sum)`

assuming you name your matrix and metacells objects "mat" and "mc"
