### ISSUE TITLE
Unable to install MetaCell

### ISSUE THREAD

**Issue by danmoore1987** [tanaylab/metacell#43]
Hi aviezerl,

I am unable to install MetaCell because of gstat:

```
ERROR:  Unix-only package
* removing 'C:/Users/danmor/Documents/R/win-library/4.0/tgstat'
Error: Failed to install 'metacell' from GitHub:
  Failed to install 'tgstat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/danmor/AppData/Local/Temp/RtmpIvTXXx/file2714303929c2/tgstat_2.3.16.tar.gz’ had non-zero exit status
```
Does the "Unix-only package" imply MetaCell can only be installed on a Unix system?
  
Thank you in advance for your help!

**Comment by aviezerl** [comment]
Hi @danmoore1987, 

Indeed `tgstat` (and `metacell`) is available only for unix and macOS. 

Aviezer
