### ISSUE TITLE
Cluster assignment is produced for only a subset of the cells post QC

### ISSUE THREAD

**Issue by asmagen** [tanaylab/metacell#47]
I am trying to cluster 4286 cells but only 1172 of them get a cluster assignment at the end of the pipeline. None of them have less than 500 UMIs, which is the lower filtering cutoff I'm using. The matrix object `attributes(mat$object)$mat` still contains 4286 cells at the end, but `attributes(mc$object)$mc` has only 1172, so I'm confused about the stage where the cells are excluded from the clustering annotation.

Also, how is mitochondrial expression treated in the metacell pipeline? I don't see any filtering of what could by dying cells.

Thank you

**Comment by akhiadber** [comment]
Please check the length of `mc@outliers` to see if it fits the missing cells length. This level of outlier filtering clearly dictates a further look at which genes cause this.

Regarding the filtering of dying cells, it is not a mandatory part of the pipeline, although highly recommended and usually performed using something like:
`mt_genes = grep('^MT-', mat@genes, perl=T, v=T)
  f_mt = colSums(mat@mat[mt_genes, ]) / colSums(mat@mat)
  mcell_mat_ignore_cells(new_mat_id, mat_id, names(which(f_mt >= max_f_mit)))` 

The definition of genes to use as markers of dying cells/cell debris might change depending on the context, so edit as you see fit.

**Comment by akhiadber** [comment]
The problem here was the T_lfc parameter, which was set at T_lfc = 2 instead of the default T_lfc = 3 .

I cannot contact @asmagen by mail anymore (weird 550 5.1.1 User Unknown after initial discussion), will update.
