### ISSUE TITLE
mcell_mat_rpt_cor_anchors error

### ISSUE THREAD

**Issue by jleandroj** [tanaylab/metacell#50]
Hello world, 

I am running this packages with 100,000 cells but I am stuck in this function mcell_mat_rpt_cor_anchors. 
I am getting this error:
 Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

Could you help me, please?

**Comment by akhiadber** [comment]
What is the RAM on your machine? 100,000 cells is only problematic if you're limited in memory.

**Comment by akhiadber** [comment]
Note that we will soon release the new metacell**s** package, with a divide and conquer approach to tackle larger datasets (in the order of millions of cells and more). While 100K cells is fine for this package as well, if you are working on a memory constrained system the new package might solve your problems.
