### ISSUE TITLE
mcell_mc_from_coclust_balanced error

### ISSUE THREAD

**Issue by jleandroj** [tanaylab/metacell#51]
Hi, 

I am running this function mcell_mc_from_coclust_balanced with your data.
I am getting this error: 

Error in thresh_K[as.numeric(names(thresh_Kr))] <- thresh_Kr : 
  NAs are not allowed in subscripted assignments
In addition: Warning message:
In mcell_coclust_filt_by_k_deg(coc_id, K, alpha) :
  NAs introduced by coercion

Could you help me, please?

**Comment by akhiadber** [comment]
This seems to be a problem with some R version that is causing the as.numeric function on the cell names to return NAs. I'm not sure yet what changed, @jleandroj please specifiy your R version, system and any other loaded packages so we can find the issue.

**Comment by akhiadber** [comment]
This issue should be solved now
