### ISSUE TITLE
Installation RSvgDevice dependency error

### ISSUE THREAD

**Issue by CFeregrino** [tanaylab/metacell#58]
Hello, I have finally got the chance to give your package a try.
But I have not been succesful installing it, since the dependency "RSvgDevice" seems to be deprecated?
It's no longer active or available from the [CRAN](https://cran.r-project.org/web/packages/RSvgDevice/index.html)
And it seems like it has been replaced with ["svglite"](https://github.com/r-lib/svglite) ?
Thanks for any answer you could give.
Cheers! - Chris

**Comment by akhiadber** [comment]
Thanks for opening this!

https://cran.r-project.org/src/contrib/Archive/RSvgDevice/
You can install it from here for a quick fix, and we will update our package accordingly as soon as we can

**Comment by lehmanbd** [comment]
I am also having the same issue and the RSvgDevice archives are not compatible with R 4.0. Any other suggestions?
best- Brian

**Comment by aviezerl** [comment]
The RSvgDevice dependency was removed in favor of svglite.
