### ISSUE TITLE
pbmc_mc_colorize table building

### ISSUE THREAD

**Issue by aviezerl** [tanaylab/metacell#6]
**[Original report](https://bitbucket.org/tanaylab/metacell/issue/6) by Anonymous.**

----------------------------------------

Hi Author,

I really like the idea and figures of MetaCell and am trying to apply it to my PBMC dataset. 

But the question is: how do I set the 'priority' parameter in pbmc_mc_colorize table? And if I want to use two cell markers to determine a cell type, how do I create it in this table? Does cell clustering heavily rely on 'priority' parameter?

Thanks and best,
Michelle

**Comment by chansigit** [comment]
hello, can you please show me the vignette's link?
