### ISSUE TITLE
mcell_mc_export_tab->Source Code may need to be modified 

### ISSUE THREAD

**Issue by XiangyangWang296** [tanaylab/metacell#70]
Hi
 When I copied source code of function `mcell_mc_export_tab`, I got error as follows:

**Error in colSums(scmat@mat[, names(mc@mc)]): 'x' must be an array of at least two dimensions**

After debuging I found once used Matrix::colSums(...) but not colSums(...) could solve this problem.

So may be the souce code of this function should be modified. Thanks.

**Comment by aviezerl** [comment]
Wierd. 
`mcell_mc_export_tab` works well in our [vignette](https://tanaylab.github.io/metacell/articles/c-metacell_annotation.html) and should automatically use the `Matrix` package `colSums` if `scmat@mat` is a sparse matrix. 
Could you maybe send us a reproducible example? What is the class of `scmat@mat`? and what are the dimensions of `scmat@mat[, names(mc@mc)]`?

**Comment by XiangyangWang296** [comment]
Sorry, some days no followed, I could not reproduce this error. Now it run OK, and the class of scmat@mat now is 'dgCMatrix'.

**Comment by aviezerl** [comment]
Great!
