### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by kimheeeeee** [tanaylab/metacell#72]
Hi,! 

I want to install metacell.
But, there is an error "ERROR: dependencies 'doMC', 'tgstat' are not available for package 'metacell'."
So I am trying to install 'doMC' and 'tgstat' , but this also cannot be installed,,
How can I solve this?

**Comment by aviezerl** [comment]
On what OS are you trying to install? Note that 'doMC' and 'tgstat' are not available for windows and therefore we currently only support Unix/macOS. If you want - you can try running metacell using WSL on your Windows machine.
