### ISSUE TITLE
Coudn't install metacell on windows

### ISSUE THREAD

**Issue by zyb1984** [tanaylab/metacell#74]
Couldn't install metacell on windows, and with ERROR message "dependency 'tgstat' is not available for package 'metacell', and from https://mirrors.sjtug.sjtu.edu.cn/cran/web/packages/tgstat/index.html, I found  "tgstat" package only suitable for UNIX

**Comment by aviezerl** [comment]
Indeed `tgstat` is currently only supported in UNIX. You can try and install `metacell` on WSL.
